"""Initial Migration

Revision ID: 153451e7f3c6
Revises: 
Create Date: 2023-10-30 21:19:52.469006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153451e7f3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_movie')
    # ### end Alembic commands ###
